version: "3"

services: 
    dns: 
        image: defreitas/dns-proxy-server
        restart: unless-stopped
        ports: 
            - "5380:5380"
        environment: 
            - hostname=dns.mageddo
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/resolv.conf:/etc/resolv.conf
    zookeeper:
        image: zookeeper
        ports: 
            - "2181:2181"
        environment: 
            - ALLOW_ANONYMOUS_LOGIN=yes
        depends_on: 
            - dns
    kafka1:
        image: bitnami/kafka
        ports: 
            - "9092:9092"
        environment: 
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_ADVERTISED_HOST_NAME=kafka1
        depends_on: 
            - zookeeper
    kafka2:
        image: bitnami/kafka
        ports: 
            - "19092:9092"
        environment: 
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_ADVERTISED_HOST_NAME=kafka2
        depends_on: 
            - zookeeper
    kafka3:
        image: bitnami/kafka
        ports: 
            - "29092:9092"
        environment: 
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_ADVERTISED_HOST_NAME=kafka3
        depends_on: 
            - zookeeper
    kafka-manager:
        image: sheepkiller/kafka-manager
        ports: 
            - "9000:9000"
        depends_on: 
            - zookeeper
            - kafka1
            - kafka2
            - kafka3
        environment: 
            - ZK_HOSTS=zookeeper:2181
            - APPLICATION_SECRET=letmein
            - KM_ARGS=-Djava.net.preferIPv4Stack=true
        depends_on: 
            - dns
    kafka-magic:
        image: digitsy/kafka-magic
        ports: 
            - "8888:80"
        depends_on: 
            - dns